# Default values for the Helm Chart.
# This is a YAML-formatted file.

units:

  # Ingress
  ingress:
    name: units
    class: traefik 
    rules:
      host: cloud.emafss.org
      http:
        path: /api/v1/units
        backend:
          service:
            name: units
            port: http

  # Service
  service:
    name: units 
    port:
      default: 80
      target: 8412

  # Deployment
  deployment:
    name: units 

  # Application / Application Replicas
  application:
    name: units
    version: 0.0.1
    image: 
      id: cloud.emafss.org:5043/units
      tag: 0.0.1
      pull:
        policy: Always
        secret: regcred
    environment: 
      postgres:
        host: bitnami-postgres-postgresql
    replicas: 1

 



