# Default values for the Helm Chart.
# This is a YAML-formatted file.

submissions:

  # Ingress
  ingress:
    name: submissions
    class: traefik 
    rules:
      host: cloud.emafss.org
      http:
        path: /api/v1/submissions
        backend:
          service:
            name: submissions
            port: http

  # Service
  service:
    name: submissions 
    port:
      default: 80
      target: 8421

  # Deployment
  deployment:
    name: submissions 

  # Application / Application Replicas
  application:
    name: submissions
    version: 0.0.1
    image: 
      id: cloud.emafss.org:5043/submissions
      tag: 0.0.1
      pull:
        policy: Always
        secret: regcred
    replicas: 1

 



