apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.submissions.deployment.name }}
  labels:
    app: {{ .Values.submissions.application.name }}
spec:
  replicas: {{ .Values.submissions.application.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.submissions.application.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.submissions.application.name }}
        version: {{ .Values.submissions.application.version }}
    spec:
      containers:
        -
          name: {{ .Values.submissions.application.name }}
          image: "{{ .Values.submissions.application.image.id }}:{{ .Values.submissions.application.image.tag }}"
          imagePullPolicy: {{ default "" .Values.submissions.application.image.pull.policy | quote }}
      imagePullSecrets:
        -
          name: {{.Values.submissions.application.image.pull.secret}}

