/*
 * Copyright (C) 2020 The Second Mile
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package ke.co.miles.submissions.util.common.observations;



/**
 *
 * @since 0.0.1
 * @author Kwaje Anthony<tony@miles.co.ke>
 * @version 1.0
 */
public enum PhenomenonTypeEnum {

	HH_DATA_ENUMERATOR_IS_MALE(1, "HH Data Enumerator is Male"),
	HH_DATA_ENUMERATOR_IS_FEMALE(2, "HH Data Enumerator is Female"),
	HH_SURVEY_RESPONDENT_IS_MALE(3, "HH Survey Respondent is Male"),
	HH_SURVEY_RESPONDENT_IS_FEMALE(4, "HH Survey Respondent is Female"),
	HH_SURVEY_RESPONDENTS_AGE(5, "HH Survey Respondent's Age"),
	HHH_IS_MALE(6, "HHH Is Male"),
	HHH_IS_FEMALE(7, "HHH Is Female"),
	HHH_IS_LESS_THAN_18_YEARS_OLD(8, "HHH Is Less Than 18 Years Old"),
	HHH_IS_BETWEEN_18_AND_35_YEARS_OLD(9, "HHH Is Between 18 And 35 Years Old"),
	HHH_IS_BETWEEN_36_AND_50_YEARS_OLD(10, "HHH Is Between 36 And 50 Years Old"),
	HHH_IS_MORE_THAN_50_YEARS_OLD(11, "HHH Is More Than 50 Years Old"),
	HH_MALE_MEMBERS(12, "HH Male Members"),
	HH_FEMALE_MEMBERS(13, "HH Female Members"),
	HH_TOTAL_MEMBERS(14, "HH Total Members"),
	HH_OBTAINS_ITS_FOOD_MAINLY_FROM_PURCHASES(15, "HH Obtains Its Food Mainly From Purchases"),
	HH_OBTAINS_ITS_FOOD_MAINLY_FROM_OWN_PRODUCTION(16, "HH Obtains Its Food Mainly From Own Production"),
	HH_OBTAINS_ITS_FOOD_MAINLY_FROM_BORROWING(17, "HH Obtains Its Food Mainly From Borrowing"),
	HH_OBTAINS_ITS_FOOD_MAINLY_FROM_FOOD_AID(18, "HH Obtains Its Food Mainly From Food Aid"),
	HH_OBTAINS_ITS_FOOD_MAINLY_FROM_GIFTS_OR_FROM_FRIENDS_NEIGHBOURS_OR_RELATIVES(19, "HH Obtains Its Food Mainly From Gifts Or From Friends, Neighbours Or Relatives"),
	HH_OBTAINS_ITS_FOOD_MAINLY_FROM_OTHER_SOURCES(20, "HH Obtains Its Food Mainly From Other Sources"),
	HH_MAKES_ITS_INCOME_MAINLY_FROM_THE_SALE_OF_CROP_FARM_PRODUCE(21, "HH Makes Its Income Mainly From The Sale of Crop/Farm Produce"),
	HH_MAKES_ITS_INCOME_MAINLY_FROM_THE_SALE_OF_LIVESTOCK_PRODUCTS_(22, "HH Makes Its Income Mainly From The Sale of Livestock Products "),
	HH_MAKES_ITS_INCOME_MAINLY_FROM_THE_SALE_OF_FISH_FISHING_(23, "HH Makes Its Income Mainly From The Sale of Fish/Fishing "),
	HH_MAKES_ITS_INCOME_MAINLY_FROM_WAGE_LABOUR_CASUAL(24, "HH Makes Its Income Mainly From Wage Labour (Casual)"),
	HH_MAKES_ITS_INCOME_MAINLY_FROM_SALARY_FORMAL_EMPLOYMENT(25, "HH Makes Its Income Mainly From Salary (Formal Employment)"),
	HH_MAKES_ITS_INCOME_MAINLY_FROM_OTHER_SOURCES(26, "HH Makes Its Income Mainly From Other Sources"),
	HH_PRODUCED_FOOD_PRODUCTS(27, "HH Produced Food Products"),
	HH_PRODUCED_PLANT_BASED_FOOD_PRODUCTS(28, "HH Produced Plant-Based Food Products"),
	HH_PRODUCED_ANIMAL_BASED_FOOD_PRODUCTS(29, "HH Produced Animal-Based Food Products"),
	HH_PRODUCED_FRUITS(30, "HH Produced Fruits"),
	HH_PRODUCED_TOMATOES(31, "HH Produced Tomatoes"),
	HH_PRODUCED_VEGETABLES(32, "HH Produced Vegetables"),
	HH_PRODUCED_BEANS(33, "HH Produced Beans"),
	HH_PRODUCED_CASSAVA(34, "HH Produced Cassava"),
	HH_PRODUCED_IRISH_POTATOES(35, "HH Produced Irish Potatoes"),
	HH_PRODUCED_SWEET_POTATOES(36, "HH Produced Sweet Potatoes"),
	HH_PRODUCED_MAIZE(37, "HH Produced Maize"),
	HH_PRODUCED_RICE(38, "HH Produced Rice"),
	HH_PRODUCED_GROUNDNUTS(39, "HH Produced Groundnuts"),
	HH_PRODUCED_BEEF(40, "HH Produced Beef"),
	HH_PRODUCED_GOAT_MEAT(41, "HH Produced Goat Meat"),
	HH_PRODUCED_PORK(42, "HH Produced Pork"),
	HH_SUFFERED_FOOD_PRODUCTS_PRODUCTION_LOSS_OR_DAMAGE(43, "HH Suffered Food Products Production Loss Or Damage"),
	HH_SUFFERED_PLANT_BASED_FOOD_PRODUCTS_PRODUCTION_LOSS_OR_DAMAGE(44, "HH Suffered Plant-Based Food Products Production Loss Or Damage"),
	HH_SUFFERED_ANIMAL_BASED_FOOD_PRODUCTS_PRODUCTION_LOSS_OR_DAMAGE(45, "HH Suffered Animal-Based Food Products Production Loss Or Damage"),
	HH_SUFFERED_FRUITS_PRODUCTION_LOSS_OR_DAMAGE(46, "HH Suffered Fruits Production Loss Or Damage"),
	HH_SUFFERED_TOMATOES_PRODUCTION_LOSS_OR_DAMAGE(47, "HH Suffered Tomatoes Production Loss Or Damage"),
	HH_SUFFERED_VEGETABLES_PRODUCTION_LOSS_OR_DAMAGE(48, "HH Suffered Vegetables Production Loss Or Damage"),
	HH_SUFFERED_BEANS_PRODUCTION_LOSS_OR_DAMAGE(49, "HH Suffered Beans Production Loss Or Damage"),
	HH_SUFFERED_CASSAVA_PRODUCTION_LOSS_OR_DAMAGE(50, "HH Suffered Cassava Production Loss Or Damage"),
	HH_SUFFERED_IRISH_POTATOES_PRODUCTION_LOSS_OR_DAMAGE(51, "HH Suffered Irish Potatoes Production Loss Or Damage"),
	HH_SUFFERED_SWEET_POTATOES_PRODUCTION_LOSS_OR_DAMAGE(52, "HH Suffered Sweet Potatoes Production Loss Or Damage"),
	HH_SUFFERED_MAIZE_PRODUCTION_LOSS_OR_DAMAGE(53, "HH Suffered Maize Production Loss Or Damage"),
	HH_SUFFERED_RICE_PRODUCTION_LOSS_OR_DAMAGE(54, "HH Suffered Rice Production Loss Or Damage"),
	HH_SUFFERED_GROUNDNUTS_PRODUCTION_LOSS_OR_DAMAGE(55, "HH Suffered Groundnuts Production Loss Or Damage"),
	HH_SUFFERED_BEEF_PRODUCTION_LOSS_OR_DAMAGE(56, "HH Suffered Beef Production Loss Or Damage"),
	HH_SUFFERED_GOAT_MEAT_PRODUCTION_LOSS_OR_DAMAGE(57, "HH Suffered Goat Meat Production Loss Or Damage"),
	HH_SUFFERED_PORK_PRODUCTION_LOSS_OR_DAMAGE(58, "HH Suffered Pork Production Loss Or Damage"),
	HH_SUFFERED_FRUITS_PRODUCTION_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_FRUITS_PRODUCED(59, "HH Suffered Fruits Production Loss Or Damage of Less Than Half of the Fruits Produced"),
	HH_SUFFERED_FRUITS_PRODUCTION_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_FRUITS_PRODUCED(60, "HH Suffered Fruits Production Loss Or Damage of About Half of the Fruits Produced"),
	HH_SUFFERED_FRUITS_PRODUCTION_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_FRUITS_PRODUCED(61, "HH Suffered Fruits Production Loss Or Damage of More Than Half of the Fruits Produced"),
	HH_SUFFERED_FRUITS_PRODUCTION_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_FRUITS_PRODUCED(62, "HH Suffered Fruits Production Loss Or Damage of Practically All of the Fruits Produced"),
	HH_SUFFERED_TOMATOES_PRODUCTION_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_TOMATOES_PRODUCED(63, "HH Suffered Tomatoes Production Loss Or Damage of Less Than Half of the Tomatoes Produced"),
	HH_SUFFERED_TOMATOES_PRODUCTION_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_TOMATOES_PRODUCED(64, "HH Suffered Tomatoes Production Loss Or Damage of About Half of the Tomatoes Produced"),
	HH_SUFFERED_TOMATOES_PRODUCTION_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_TOMATOES_PRODUCED(65, "HH Suffered Tomatoes Production Loss Or Damage of More Than Half of the Tomatoes Produced"),
	HH_SUFFERED_TOMATOES_PRODUCTION_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_TOMATOES_PRODUCED(66, "HH Suffered Tomatoes Production Loss Or Damage of Practically All of the Tomatoes Produced"),
	HH_SUFFERED_VEGETABLES_PRODUCTION_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_VEGETABLES_PRODUCED(67, "HH Suffered Vegetables Production Loss Or Damage of Less Than Half of the Vegetables Produced"),
	HH_SUFFERED_VEGETABLES_PRODUCTION_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_VEGETABLES_PRODUCED(68, "HH Suffered Vegetables Production Loss Or Damage of About Half of the Vegetables Produced"),
	HH_SUFFERED_VEGETABLES_PRODUCTION_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_VEGETABLES_PRODUCED(69, "HH Suffered Vegetables Production Loss Or Damage of More Than Half of the Vegetables Produced"),
	HH_SUFFERED_VEGETABLES_PRODUCTION_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_VEGETABLES_PRODUCED(70, "HH Suffered Vegetables Production Loss Or Damage of Practically All of the Vegetables Produced"),
	HH_SUFFERED_BEANS_PRODUCTION_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_BEANS_PRODUCED(71, "HH Suffered Beans Production Loss Or Damage of Less Than Half of the Beans Produced"),
	HH_SUFFERED_BEANS_PRODUCTION_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_BEANS_PRODUCED(72, "HH Suffered Beans Production Loss Or Damage of About Half of the Beans Produced"),
	HH_SUFFERED_BEANS_PRODUCTION_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_BEANS_PRODUCED(73, "HH Suffered Beans Production Loss Or Damage of More Than Half of the Beans Produced"),
	HH_SUFFERED_BEANS_PRODUCTION_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_BEANS_PRODUCED(74, "HH Suffered Beans Production Loss Or Damage of Practically All of the Beans Produced"),
	HH_SUFFERED_CASSAVA_PRODUCTION_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_CASSAVA_PRODUCED(75, "HH Suffered Cassava Production Loss Or Damage of Less Than Half of the Cassava Produced"),
	HH_SUFFERED_CASSAVA_PRODUCTION_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_CASSAVA_PRODUCED(76, "HH Suffered Cassava Production Loss Or Damage of About Half of the Cassava Produced"),
	HH_SUFFERED_CASSAVA_PRODUCTION_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_CASSAVA_PRODUCED(77, "HH Suffered Cassava Production Loss Or Damage of More Than Half of the Cassava Produced"),
	HH_SUFFERED_CASSAVA_PRODUCTION_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_CASSAVA_PRODUCED(78, "HH Suffered Cassava Production Loss Or Damage of Practically All of the Cassava Produced"),
	HH_SUFFERED_IRISH_POTATOES_PRODUCTION_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_IRISH_POTATOES_PRODUCED(79, "HH Suffered Irish Potatoes Production Loss Or Damage of Less Than Half of the Irish Potatoes Produced"),
	HH_SUFFERED_IRISH_POTATOES_PRODUCTION_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_IRISH_POTATOES_PRODUCED(80, "HH Suffered Irish Potatoes Production Loss Or Damage of About Half of the Irish Potatoes Produced"),
	HH_SUFFERED_IRISH_POTATOES_PRODUCTION_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_IRISH_POTATOES_PRODUCED(81, "HH Suffered Irish Potatoes Production Loss Or Damage of More Than Half of the Irish Potatoes Produced"),
	HH_SUFFERED_IRISH_POTATOES_PRODUCTION_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_IRISH_POTATOES_PRODUCED(82, "HH Suffered Irish Potatoes Production Loss Or Damage of Practically All of the Irish Potatoes Produced"),
	HH_SUFFERED_SWEET_POTATOES_PRODUCTION_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_SWEET_POTATOES_PRODUCED(83, "HH Suffered Sweet Potatoes Production Loss Or Damage of Less Than Half of the Sweet Potatoes Produced"),
	HH_SUFFERED_SWEET_POTATOES_PRODUCTION_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_SWEET_POTATOES_PRODUCED(84, "HH Suffered Sweet Potatoes Production Loss Or Damage of About Half of the Sweet Potatoes Produced"),
	HH_SUFFERED_SWEET_POTATOES_PRODUCTION_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_SWEET_POTATOES_PRODUCED(85, "HH Suffered Sweet Potatoes Production Loss Or Damage of More Than Half of the Sweet Potatoes Produced"),
	HH_SUFFERED_SWEET_POTATOES_PRODUCTION_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_SWEET_POTATOES_PRODUCED(86, "HH Suffered Sweet Potatoes Production Loss Or Damage of Practically All of the Sweet Potatoes Produced"),
	HH_SUFFERED_MAIZE_PRODUCTION_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_MAIZE_PRODUCED(87, "HH Suffered Maize Production Loss Or Damage of Less Than Half of the Maize Produced"),
	HH_SUFFERED_MAIZE_PRODUCTION_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_MAIZE_PRODUCED(88, "HH Suffered Maize Production Loss Or Damage of About Half of the Maize Produced"),
	HH_SUFFERED_MAIZE_PRODUCTION_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_MAIZE_PRODUCED(89, "HH Suffered Maize Production Loss Or Damage of More Than Half of the Maize Produced"),
	HH_SUFFERED_MAIZE_PRODUCTION_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_MAIZE_PRODUCED(90, "HH Suffered Maize Production Loss Or Damage of Practically All of the Maize Produced"),
	HH_SUFFERED_RICE_PRODUCTION_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_RICE_PRODUCED(91, "HH Suffered Rice Production Loss Or Damage of Less Than Half of the Rice Produced"),
	HH_SUFFERED_RICE_PRODUCTION_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_RICE_PRODUCED(92, "HH Suffered Rice Production Loss Or Damage of About Half of the Rice Produced"),
	HH_SUFFERED_RICE_PRODUCTION_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_RICE_PRODUCED(93, "HH Suffered Rice Production Loss Or Damage of More Than Half of the Rice Produced"),
	HH_SUFFERED_RICE_PRODUCTION_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_RICE_PRODUCED(94, "HH Suffered Rice Production Loss Or Damage of Practically All of the Rice Produced"),
	HH_SUFFERED_GROUNDNUTS_PRODUCTION_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_GROUNDNUTS_PRODUCED(95, "HH Suffered Groundnuts Production Loss Or Damage of Less Than Half of the Groundnuts Produced"),
	HH_SUFFERED_GROUNDNUTS_PRODUCTION_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_GROUNDNUTS_PRODUCED(96, "HH Suffered Groundnuts Production Loss Or Damage of About Half of the Groundnuts Produced"),
	HH_SUFFERED_GROUNDNUTS_PRODUCTION_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_GROUNDNUTS_PRODUCED(97, "HH Suffered Groundnuts Production Loss Or Damage of More Than Half of the Groundnuts Produced"),
	HH_SUFFERED_GROUNDNUTS_PRODUCTION_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_GROUNDNUTS_PRODUCED(98, "HH Suffered Groundnuts Production Loss Or Damage of Practically All of the Groundnuts Produced"),
	HH_SUFFERED_BEEF_PRODUCTION_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_BEEF_PRODUCED(99, "HH Suffered Beef Production Loss Or Damage of Less Than Half of the Beef Produced"),
	HH_SUFFERED_BEEF_PRODUCTION_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_BEEF_PRODUCED(100, "HH Suffered Beef Production Loss Or Damage of About Half of the Beef Produced"),
	HH_SUFFERED_BEEF_PRODUCTION_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_BEEF_PRODUCED(101, "HH Suffered Beef Production Loss Or Damage of More Than Half of the Beef Produced"),
	HH_SUFFERED_BEEF_PRODUCTION_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_BEEF_PRODUCED(102, "HH Suffered Beef Production Loss Or Damage of Practically All of the Beef Produced"),
	HH_SUFFERED_GOAT_MEAT_PRODUCTION_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_GOAT_MEAT_PRODUCED(103, "HH Suffered Goat Meat Production Loss Or Damage of Less Than Half of the Goat Meat Produced"),
	HH_SUFFERED_GOAT_MEAT_PRODUCTION_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_GOAT_MEAT_PRODUCED(104, "HH Suffered Goat Meat Production Loss Or Damage of About Half of the Goat Meat Produced"),
	HH_SUFFERED_GOAT_MEAT_PRODUCTION_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_GOAT_MEAT_PRODUCED(105, "HH Suffered Goat Meat Production Loss Or Damage of More Than Half of the Goat Meat Produced"),
	HH_SUFFERED_GOAT_MEAT_PRODUCTION_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_GOAT_MEAT_PRODUCED(106, "HH Suffered Goat Meat Production Loss Or Damage of Practically All of the Goat Meat Produced"),
	HH_SUFFERED_PORK_PRODUCTION_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_PORK_PRODUCED(107, "HH Suffered Pork Production Loss Or Damage of Less Than Half of the Pork Produced"),
	HH_SUFFERED_PORK_PRODUCTION_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_PORK_PRODUCED(108, "HH Suffered Pork Production Loss Or Damage of About Half of the Pork Produced"),
	HH_SUFFERED_PORK_PRODUCTION_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_PORK_PRODUCED(109, "HH Suffered Pork Production Loss Or Damage of More Than Half of the Pork Produced"),
	HH_SUFFERED_PORK_PRODUCTION_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_PORK_PRODUCED(110, "HH Suffered Pork Production Loss Or Damage of Practically All of the Pork Produced"),
	HH_SUFFERED_POST_HARVEST_LOSS_OR_DAMAGE_DUE_TO_LACK_OF_MARKET(111, "HH suffered Post Harvest Loss Or Damage Due to Lack of Market"),
	HH_SUFFERED_POST_HARVEST_LOSS_OR_DAMAGE_DUE_TO_PESTS(112, "HH suffered Post Harvest Loss Or Damage Due to Pests"),
	HH_SUFFERED_POST_HARVEST_LOSS_OR_DAMAGE_DUE_TO_OVERPRODUCTION(113, "HH suffered Post Harvest Loss Or Damage Due to Overproduction"),
	HH_SUFFERED_POST_HARVEST_LOSS_OR_DAMAGE_DUE_TO_LACK_OF_STORAGE(114, "HH suffered Post Harvest Loss Or Damage Due to Lack of Storage"),
	HH_SUFFERED_POST_HARVEST_LOSS_OR_DAMAGE_DUE_TO_LACK_OF_LABOR_SUPPLY(115, "HH suffered Post Harvest Loss Or Damage Due to Lack of Labor Supply"),
	HH_SUFFERED_POST_HARVEST_LOSS_OR_DAMAGE_DUE_TO_LACK_OF_TRANSPORTATION(116, "HH suffered Post Harvest Loss Or Damage Due to Lack of Transportation"),
	HH_SUFFERED_POST_HARVEST_LOSS_OR_DAMAGE_DUE_TO_UNTIMELY_HARVEST(117, "HH suffered Post Harvest Loss Or Damage Due to Untimely harvest"),
	HH_SUFFERED_POST_HARVEST_LOSS_OR_DAMAGE_DUE_TO_OTHER_REASONS(118, "HH suffered Post Harvest Loss Or Damage Due to Other Reasons"),
	HH_SUFFERED_FOOD_SCARCITY(119, "HH Suffered Food Scarcity"),
	LENGTH_OF_TIME_HH_HAD_TO_RELY_ON_LESS_PREFERRED_AND_LESS_EXPENSIVE_FOOD(120, "Length Of Time HH Had To Rely On Less Preferred And Less Expensive Food"),
	LENGTH_OF_TIME_HH_HAD_TO_BORROW_FOOD_OR_RELY_ON_HELP_FROM_A_FRIEND_OR_RELATIVE(121, "Length Of Time HH Had To Borrow Food, Or Rely On Help From A Friend Or Relative"),
	LENGTH_OF_TIME_HH_HAD_TO_LIMIT_PORTION_SIZE_AT_MEAL_TIMES(122, "Length Of Time HH Had To Limit Portion Size At Meal Times"),
	LENGTH_OF_TIME_HH_HAD_TO_RESTRICT_CONSUMPTION_BY_ADULTS_IN_ORDER_FOR_SMALL_CHILDREN_TO_EAT(123, "Length Of Time HH Had To Restrict Consumption By Adults In Order For Small Children To Eat"),
	LENGTH_OF_TIME_HH_HAD_TO_REDUCE_NUMBER_OF_MEALS_EATEN_IN_A_DAY(124, "Length Of Time HH Had To Reduce Number Of Meals Eaten In A Day"),
	HH_REARS_LIVESTOCK(125, "HH Rears Livestock"),
	HH_REARS_CATTLE(126, "HH Rears Cattle"),
	HH_REARS_GOATS(127, "HH Rears Goats"),
	HH_REARS_PIG(128, "HH Rears Pig"),
	HH_LIVESTOCK_WERE_ATTACKED_BY_A_DISEASE(129, "HH Livestock Were Attacked By a Disease"),
	HH_LIVESTOCK_WERE_ATTACKED_BY_NEWCASTLE_DISEASE(130, "HH Livestock Were Attacked By Newcastle Disease"),
	HH_LIVESTOCK_WERE_ATTACKED_BY_FOOT_AND_MOUTH_DISEASE(131, "HH Livestock Were Attacked By Foot and Mouth Disease"),
	HH_LIVESTOCK_WERE_ATTACKED_BY_AFRICAN_SWINE_FEVER_DISEASE(132, "HH Livestock Were Attacked By African Swine Fever Disease"),
	HH_LIVESTOCK_WERE_ATTACKED_BY_MANGE_DISEASE(133, "HH Livestock Were Attacked By Mange Disease"),
	HH_LIVESTOCK_WERE_ATTACKED_BY_SMALL_POX_DISEASE(134, "HH Livestock Were Attacked By Small Pox Disease"),
	HH_LIVESTOCK_WERE_ATTACKED_BY_OTHER_DISEASES(135, "HH Livestock Were Attacked By Other Diseases"),
	HH_LIVESTOCK_REQUIRED_MEDICATION(136, "HH Livestock Required Medication"),
	HH_ACCESSED_ANIMAL_HEALTH_SERVICES_FOR_ITS_LIVESTOCK(137, "HH accessed Animal Health Services For Its Livestock"),
	HH_DID_NOT_ACCESS_ANIMAL_HEALTH_SERVICES_BECAUSE_OF_LACK_SUPPLY_OF_DRUGS_AND_VACCINES(138, "HH Did Not Access Animal Health Services Because Of Lack Supply Of Drugs And Vaccines"),
	HH_DID_NOT_ACCESS_ANIMAL_HEALTH_SERVICES_BECAUSE_OF_LACK_OF_MONEY_TO_BUY_THE_SUPPLIES_WITH(139, "HH Did Not Access Animal Health Services Because Of Lack Of Money To Buy The Supplies With"),
	HH_DID_NOT_ACCESS_ANIMAL_HEALTH_SERVICES_BECAUSE_OF_OTHER_REASONS(140, "HH Did Not Access Animal Health Services Because Of Other Reasons"),
	HH_HAD_ACCESS_TO_FARM_INPUTS(141, "HH Had Access To Farm Inputs"),
	HH_HAD_ACCESS_TO_SEEDS_GRAINS_VEGETABLES_LEGUMES(142, "HH Had Access To Seeds (Grains/vegetables/legumes)"),
	HH_HAD_ACCESS_TO_STORAGE_EQUIPMENT_SACKS(143, "HH Had Access To Storage Equipment (Sacks)"),
	HH_HAD_ACCESS_TO_FERTILIZERS(144, "HH Had Access To Fertilizers"),
	HH_HAD_ACCESS_TO_GRAIN_PRESERVATIVES_EGACTELIC_SHUMBA(145, "HH Had Access To Grain Preservatives (eg.Actelic, Shumba)"),
	HH_HAD_ACCESS_TO_CROP_CHEMICALS_HERBICIDES_PESTICIDES_FUNGICIDES(146, "HH Had Access To Crop Chemicals (Herbicides, Pesticides, Fungicides)"),
	HH_HAD_ACCESS_TO_VACCINES_FOR_LIVESTOCK(147, "HH Had Access To Vaccines For Livestock"),
	HH_HAD_ACCESS_TO_VETERINARY_DRUGS(148, "HH Had Access To Veterinary Drugs"),
	HH_HAD_ACCESS_TO_OTHERS_FARM_IMPLEMENTS(149, "HH Had Access To Others Farm Implements"),
	HH_DID_NOT_ACCESS_INPUTS_BECAUSE_IT_DOES_NOT_USUALLY_USE_INPUTS(150, "HH Did Not Access Inputs Because It Does Not Usually Use Inputs"),
	HH_DID_NOT_ACCESS_INPUTS_BECAUSE_AGRO_DEALER_SHOPS_ARE_NOT_OPEN_DUE_TO_ADMINISTRATIVE_RESTRICTIONS(151, "HH Did Not Access Inputs Because Agro Dealer Shops Are Not Open Due To Administrative Restrictions"),
	HH_DID_NOT_ACCESS_INPUTS_BECAUSE_AGRO_DEALER_SHOPS_ARE_FAR_AND_CANT_MAKE_IT_WITHIN_STIPULATED_RESTRICTION_TIMES(152, "HH Did Not Access Inputs Because Agro Dealer Shops Are Far And Can't Make It Within Stipulated Restriction Times."),
	HH_DID_NOT_ACCESS_INPUTS_BECAUSE_AGRO_DEALER_SHOPS_ARE_OPEN_BUT_INPUTS_ARE_NOT_AVAILABLE(153, "HH Did Not Access Inputs Because Agro Dealer Shops Are Open But Inputs Are Not Available"),
	HH_DID_NOT_ACCESS_INPUTS_BECAUSE_OF_OTHER_REASONS(154, "HH Did Not Access Inputs Because Of Other Reasons"),
	MARKETS_DATA_ENUMERATOR_IS_MALE(155, "Market's Data Enumerator is Male"),
	MARKETS_DATA_ENUMERATOR_IS_FEMALE(156, "Market's Data Enumerator is Female"),
	MARKET_IS_FUNCTIONAL(157, "Market Is Functional"),
	MARKET_IS_CLOSED_DUE_TO_LACK_OF_AGRICULTURAL_PRODUCE(158, "Market Is Closed Due To Lack of Agricultural Produce"),
	MARKET_IS_CLOSED_DUE_TO_A_DIRECTIVE_FROM_NATIONAL_OR_LOCAL_GOVERNMENT_ON_MARKET_CLOSURE(159, "Market Is Closed Due To A Directive From National Or Local Government On Market Closure"),
	MARKET_IS_CLOSED_DUE_TO_OTHER_REASONS(160, "Market Is Closed Due To Other Reasons"),
	MARKET_HAD_NO_FRUITS(161, "Market Had No Fruits"),
	MARKET_HAD_ALMOST_NO_FRUITS(162, "Market Had Almost No Fruits"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_FRUITS(163, "Market Had Less Than Half The Usual Amount Of Fruits"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_FRUITS(164, "Market Had Almost Half The Usual Amount Of Fruits"),
	MARKET_HAD_FRUITS_READILY_AVAILABLE(165, "Market Had Fruits Readily Available"),
	MARKET_HAD_NO_TOMATOES(166, "Market Had No Tomatoes"),
	MARKET_HAD_ALMOST_NO_TOMATOES(167, "Market Had Almost No Tomatoes"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_TOMATOES(168, "Market Had Less Than Half The Usual Amount Of Tomatoes"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_TOMATOES(169, "Market Had Almost Half The Usual Amount Of Tomatoes"),
	MARKET_HAD_TOMATOES_READILY_AVAILABLE(170, "Market Had Tomatoes Readily Available"),
	MARKET_HAD_NO_VEGETABLES(171, "Market Had No Vegetables"),
	MARKET_HAD_ALMOST_NO_VEGETABLES(172, "Market Had Almost No Vegetables"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_VEGETABLES(173, "Market Had Less Than Half The Usual Amount Of Vegetables"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_VEGETABLES(174, "Market Had Almost Half The Usual Amount Of Vegetables"),
	MARKET_HAD_VEGETABLES_READILY_AVAILABLE(175, "Market Had Vegetables Readily Available"),
	MARKET_HAD_NO_BEANS(176, "Market Had No Beans"),
	MARKET_HAD_ALMOST_NO_BEANS(177, "Market Had Almost No Beans"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_BEANS(178, "Market Had Less Than Half The Usual Amount Of Beans"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_BEANS(179, "Market Had Almost Half The Usual Amount Of Beans"),
	MARKET_HAD_BEANS_READILY_AVAILABLE(180, "Market Had Beans Readily Available"),
	MARKET_HAD_NO_CASSAVA(181, "Market Had No Cassava"),
	MARKET_HAD_ALMOST_NO_CASSAVA(182, "Market Had Almost No Cassava"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_CASSAVA(183, "Market Had Less Than Half The Usual Amount Of Cassava"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_CASSAVA(184, "Market Had Almost Half The Usual Amount Of Cassava"),
	MARKET_HAD_CASSAVA_READILY_AVAILABLE(185, "Market Had Cassava Readily Available"),
	MARKET_HAD_NO_IRISH_POTATOES(186, "Market Had No Irish Potatoes"),
	MARKET_HAD_ALMOST_NO_IRISH_POTATOES(187, "Market Had Almost No Irish Potatoes"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_IRISH_POTATOES(188, "Market Had Less Than Half The Usual Amount Of Irish Potatoes"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_IRISH_POTATOES(189, "Market Had Almost Half The Usual Amount Of Irish Potatoes"),
	MARKET_HAD_IRISH_POTATOES_READILY_AVAILABLE(190, "Market Had Irish Potatoes Readily Available"),
	MARKET_HAD_NO_SWEET_POTATOES(191, "Market Had No Sweet Potatoes"),
	MARKET_HAD_ALMOST_NO_SWEET_POTATOES(192, "Market Had Almost No Sweet Potatoes"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_SWEET_POTATOES(193, "Market Had Less Than Half The Usual Amount Of Sweet Potatoes"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_SWEET_POTATOES(194, "Market Had Almost Half The Usual Amount Of Sweet Potatoes"),
	MARKET_HAD_SWEET_POTATOES_READILY_AVAILABLE(195, "Market Had Sweet Potatoes Readily Available"),
	MARKET_HAD_NO_MAIZE(196, "Market Had No Maize"),
	MARKET_HAD_ALMOST_NO_MAIZE(197, "Market Had Almost No Maize"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_MAIZE(198, "Market Had Less Than Half The Usual Amount Of Maize"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_MAIZE(199, "Market Had Almost Half The Usual Amount Of Maize"),
	MARKET_HAD_MAIZE_READILY_AVAILABLE(200, "Market Had Maize Readily Available"),
	MARKET_HAD_NO_RICE(201, "Market Had No Rice"),
	MARKET_HAD_ALMOST_NO_RICE(202, "Market Had Almost No Rice"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_RICE(203, "Market Had Less Than Half The Usual Amount Of Rice"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_RICE(204, "Market Had Almost Half The Usual Amount Of Rice"),
	MARKET_HAD_RICE_READILY_AVAILABLE(205, "Market Had Rice Readily Available"),
	MARKET_HAD_NO_GROUNDNUTS(206, "Market Had No Groundnuts"),
	MARKET_HAD_ALMOST_NO_GROUNDNUTS(207, "Market Had Almost No Groundnuts"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_GROUNDNUTS(208, "Market Had Less Than Half The Usual Amount Of Groundnuts"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_GROUNDNUTS(209, "Market Had Almost Half The Usual Amount Of Groundnuts"),
	MARKET_HAD_GROUNDNUTS_READILY_AVAILABLE(210, "Market Had Groundnuts Readily Available"),
	MARKET_HAD_NO_BEEF(211, "Market Had No Beef"),
	MARKET_HAD_ALMOST_NO_BEEF(212, "Market Had Almost No Beef"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_BEEF(213, "Market Had Less Than Half The Usual Amount Of Beef"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_BEEF(214, "Market Had Almost Half The Usual Amount Of Beef"),
	MARKET_HAD_BEEF_READILY_AVAILABLE(215, "Market Had Beef Readily Available"),
	MARKET_HAD_NO_GOAT_MEAT(216, "Market Had No Goat Meat"),
	MARKET_HAD_ALMOST_NO_GOAT_MEAT(217, "Market Had Almost No Goat Meat"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_GOAT_MEAT(218, "Market Had Less Than Half The Usual Amount Of Goat Meat"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_GOAT_MEAT(219, "Market Had Almost Half The Usual Amount Of Goat Meat"),
	MARKET_HAD_GOAT_MEAT_READILY_AVAILABLE(220, "Market Had Goat Meat Readily Available"),
	MARKET_HAD_NO_PORK(221, "Market Had No Pork"),
	MARKET_HAD_ALMOST_NO_PORK(222, "Market Had Almost No Pork"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_PORK(223, "Market Had Less Than Half The Usual Amount Of Pork"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_PORK(224, "Market Had Almost Half The Usual Amount Of Pork"),
	MARKET_HAD_PORK_READILY_AVAILABLE(225, "Market Had Pork Readily Available"),
	MARKET_HAD_NO_FISH(226, "Market Had No Fish"),
	MARKET_HAD_ALMOST_NO_FISH(227, "Market Had Almost No Fish"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_FISH(228, "Market Had Less Than Half The Usual Amount Of Fish"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_FISH(229, "Market Had Almost Half The Usual Amount Of Fish"),
	MARKET_HAD_FISH_READILY_AVAILABLE(230, "Market Had Fish Readily Available"),
	MARKET_HAD_NO_LIVE_CATTLE(231, "Market Had No Live Cattle"),
	MARKET_HAD_ALMOST_NO_LIVE_CATTLE(232, "Market Had Almost No Live Cattle"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_LIVE_CATTLE(233, "Market Had Less Than Half The Usual Amount Of Live Cattle"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_LIVE_CATTLE(234, "Market Had Almost Half The Usual Amount Of Live Cattle"),
	MARKET_HAD_LIVE_CATTLE_READILY_AVAILABLE(235, "Market Had Live Cattle Readily Available"),
	MARKET_HAD_NO_LIVE_GOATS(236, "Market Had No Live Goats"),
	MARKET_HAD_ALMOST_NO_LIVE_GOATS(237, "Market Had Almost No Live Goats"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_LIVE_GOATS(238, "Market Had Less Than Half The Usual Amount Of Live Goats"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_LIVE_GOATS(239, "Market Had Almost Half The Usual Amount Of Live Goats"),
	MARKET_HAD_LIVE_GOATS_READILY_AVAILABLE(240, "Market Had Live Goats Readily Available"),
	MARKET_HAD_NO_LIVE_CHICKENS(241, "Market Had No Live Chickens"),
	MARKET_HAD_ALMOST_NO_LIVE_CHICKENS(242, "Market Had Almost No Live Chickens"),
	MARKET_HAD_LESS_THAN_HALF_THE_USUAL_AMOUNT_OF_LIVE_CHICKENS(243, "Market Had Less Than Half The Usual Amount Of Live Chickens"),
	MARKET_HAD_ALMOST_HALF_THE_USUAL_AMOUNT_OF_LIVE_CHICKENS(244, "Market Had Almost Half The Usual Amount Of Live Chickens"),
	MARKET_HAD_LIVE_CHICKENS_READILY_AVAILABLE(245, "Market Had Live Chickens Readily Available"),
	MARKET_FIRSTLY_SOURCED_FRUITS_LOCALLY_WITHIN_THE_DISTRICT(246, "Market Firstly Sourced Fruits Locally (Within the District)"),
	MARKET_FIRSTLY_SOURCED_FRUITS_FROM_NEIGHBORING_DISTRICTS(247, "Market Firstly Sourced Fruits From Neighboring Districts"),
	MARKET_FIRSTLY_SOURCED_FRUITS_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(248, "Market Firstly Sourced Fruits From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_FIRSTLY_SOURCED_TOMATOES_LOCALLY_WITHIN_THE_DISTRICT(249, "Market Firstly Sourced Tomatoes Locally (Within the District)"),
	MARKET_FIRSTLY_SOURCED_TOMATOES_FROM_NEIGHBORING_DISTRICTS(250, "Market Firstly Sourced Tomatoes From Neighboring Districts"),
	MARKET_FIRSTLY_SOURCED_TOMATOES_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(251, "Market Firstly Sourced Tomatoes From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_FIRSTLY_SOURCED_VEGETABLES_LOCALLY_WITHIN_THE_DISTRICT(252, "Market Firstly Sourced Vegetables Locally (Within the District)"),
	MARKET_FIRSTLY_SOURCED_VEGETABLES_FROM_NEIGHBORING_DISTRICTS(253, "Market Firstly Sourced Vegetables From Neighboring Districts"),
	MARKET_FIRSTLY_SOURCED_VEGETABLES_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(254, "Market Firstly Sourced Vegetables From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_FIRSTLY_SOURCED_BEANS_LOCALLY_WITHIN_THE_DISTRICT(255, "Market Firstly Sourced Beans Locally (Within the District)"),
	MARKET_FIRSTLY_SOURCED_BEANS_FROM_NEIGHBORING_DISTRICTS(256, "Market Firstly Sourced Beans From Neighboring Districts"),
	MARKET_FIRSTLY_SOURCED_BEANS_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(257, "Market Firstly Sourced Beans From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_FIRSTLY_SOURCED_CASSAVA_LOCALLY_WITHIN_THE_DISTRICT(258, "Market Firstly Sourced Cassava Locally (Within the District)"),
	MARKET_FIRSTLY_SOURCED_CASSAVA_FROM_NEIGHBORING_DISTRICTS(259, "Market Firstly Sourced Cassava From Neighboring Districts"),
	MARKET_FIRSTLY_SOURCED_CASSAVA_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(260, "Market Firstly Sourced Cassava From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_FIRSTLY_SOURCED_IRISH_POTATOES_LOCALLY_WITHIN_THE_DISTRICT(261, "Market Firstly Sourced Irish Potatoes Locally (Within the District)"),
	MARKET_FIRSTLY_SOURCED_IRISH_POTATOES_FROM_NEIGHBORING_DISTRICTS(262, "Market Firstly Sourced Irish Potatoes From Neighboring Districts"),
	MARKET_FIRSTLY_SOURCED_IRISH_POTATOES_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(263, "Market Firstly Sourced Irish Potatoes From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_FIRSTLY_SOURCED_SWEET_POTATOES_LOCALLY_WITHIN_THE_DISTRICT(264, "Market Firstly Sourced Sweet Potatoes Locally (Within the District)"),
	MARKET_FIRSTLY_SOURCED_SWEET_POTATOES_FROM_NEIGHBORING_DISTRICTS(265, "Market Firstly Sourced Sweet Potatoes From Neighboring Districts"),
	MARKET_FIRSTLY_SOURCED_SWEET_POTATOES_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(266, "Market Firstly Sourced Sweet Potatoes From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_FIRSTLY_SOURCED_MAIZE_LOCALLY_WITHIN_THE_DISTRICT(267, "Market Firstly Sourced Maize Locally (Within the District)"),
	MARKET_FIRSTLY_SOURCED_MAIZE_FROM_NEIGHBORING_DISTRICTS(268, "Market Firstly Sourced Maize From Neighboring Districts"),
	MARKET_FIRSTLY_SOURCED_MAIZE_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(269, "Market Firstly Sourced Maize From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_FIRSTLY_SOURCED_RICE_LOCALLY_WITHIN_THE_DISTRICT(270, "Market Firstly Sourced Rice Locally (Within the District)"),
	MARKET_FIRSTLY_SOURCED_RICE_FROM_NEIGHBORING_DISTRICTS(271, "Market Firstly Sourced Rice From Neighboring Districts"),
	MARKET_FIRSTLY_SOURCED_RICE_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(272, "Market Firstly Sourced Rice From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_FIRSTLY_SOURCED_GROUNDNUTS_LOCALLY_WITHIN_THE_DISTRICT(273, "Market Firstly Sourced Groundnuts Locally (Within the District)"),
	MARKET_FIRSTLY_SOURCED_GROUNDNUTS_FROM_NEIGHBORING_DISTRICTS(274, "Market Firstly Sourced Groundnuts From Neighboring Districts"),
	MARKET_FIRSTLY_SOURCED_GROUNDNUTS_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(275, "Market Firstly Sourced Groundnuts From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_SECONDLY_SOURCED_FRUITS_LOCALLY_WITHIN_THE_DISTRICT(276, "Market Secondly Sourced Fruits Locally (Within the District)"),
	MARKET_SECONDLY_SOURCED_FRUITS_FROM_NEIGHBORING_DISTRICTS(277, "Market Secondly Sourced Fruits From Neighboring Districts"),
	MARKET_SECONDLY_SOURCED_FRUITS_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(278, "Market Secondly Sourced Fruits From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_SECONDLY_SOURCED_TOMATOES_LOCALLY_WITHIN_THE_DISTRICT(279, "Market Secondly Sourced Tomatoes Locally (Within the District)"),
	MARKET_SECONDLY_SOURCED_TOMATOES_FROM_NEIGHBORING_DISTRICTS(280, "Market Secondly Sourced Tomatoes From Neighboring Districts"),
	MARKET_SECONDLY_SOURCED_TOMATOES_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(281, "Market Secondly Sourced Tomatoes From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_SECONDLY_SOURCED_VEGETABLES_LOCALLY_WITHIN_THE_DISTRICT(282, "Market Secondly Sourced Vegetables Locally (Within the District)"),
	MARKET_SECONDLY_SOURCED_VEGETABLES_FROM_NEIGHBORING_DISTRICTS(283, "Market Secondly Sourced Vegetables From Neighboring Districts"),
	MARKET_SECONDLY_SOURCED_VEGETABLES_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(284, "Market Secondly Sourced Vegetables From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_SECONDLY_SOURCED_BEANS_LOCALLY_WITHIN_THE_DISTRICT(285, "Market Secondly Sourced Beans Locally (Within the District)"),
	MARKET_SECONDLY_SOURCED_BEANS_FROM_NEIGHBORING_DISTRICTS(286, "Market Secondly Sourced Beans From Neighboring Districts"),
	MARKET_SECONDLY_SOURCED_BEANS_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(287, "Market Secondly Sourced Beans From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_SECONDLY_SOURCED_CASSAVA_LOCALLY_WITHIN_THE_DISTRICT(288, "Market Secondly Sourced Cassava Locally (Within the District)"),
	MARKET_SECONDLY_SOURCED_CASSAVA_FROM_NEIGHBORING_DISTRICTS(289, "Market Secondly Sourced Cassava From Neighboring Districts"),
	MARKET_SECONDLY_SOURCED_CASSAVA_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(290, "Market Secondly Sourced Cassava From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_SECONDLY_SOURCED_IRISH_POTATOES_LOCALLY_WITHIN_THE_DISTRICT(291, "Market Secondly Sourced Irish Potatoes Locally (Within the District)"),
	MARKET_SECONDLY_SOURCED_IRISH_POTATOES_FROM_NEIGHBORING_DISTRICTS(292, "Market Secondly Sourced Irish Potatoes From Neighboring Districts"),
	MARKET_SECONDLY_SOURCED_IRISH_POTATOES_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(293, "Market Secondly Sourced Irish Potatoes From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_SECONDLY_SOURCED_SWEET_POTATOES_LOCALLY_WITHIN_THE_DISTRICT(294, "Market Secondly Sourced Sweet Potatoes Locally (Within the District)"),
	MARKET_SECONDLY_SOURCED_SWEET_POTATOES_FROM_NEIGHBORING_DISTRICTS(295, "Market Secondly Sourced Sweet Potatoes From Neighboring Districts"),
	MARKET_SECONDLY_SOURCED_SWEET_POTATOES_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(296, "Market Secondly Sourced Sweet Potatoes From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_SECONDLY_SOURCED_MAIZE_LOCALLY_WITHIN_THE_DISTRICT(297, "Market Secondly Sourced Maize Locally (Within the District)"),
	MARKET_SECONDLY_SOURCED_MAIZE_FROM_NEIGHBORING_DISTRICTS(298, "Market Secondly Sourced Maize From Neighboring Districts"),
	MARKET_SECONDLY_SOURCED_MAIZE_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(299, "Market Secondly Sourced Maize From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_SECONDLY_SOURCED_RICE_LOCALLY_WITHIN_THE_DISTRICT(300, "Market Secondly Sourced Rice Locally (Within the District)"),
	MARKET_SECONDLY_SOURCED_RICE_FROM_NEIGHBORING_DISTRICTS(301, "Market Secondly Sourced Rice From Neighboring Districts"),
	MARKET_SECONDLY_SOURCED_RICE_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(302, "Market Secondly Sourced Rice From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_SECONDLY_SOURCED_GROUNDNUTS_LOCALLY_WITHIN_THE_DISTRICT(303, "Market Secondly Sourced Groundnuts Locally (Within the District)"),
	MARKET_SECONDLY_SOURCED_GROUNDNUTS_FROM_NEIGHBORING_DISTRICTS(304, "Market Secondly Sourced Groundnuts From Neighboring Districts"),
	MARKET_SECONDLY_SOURCED_GROUNDNUTS_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(305, "Market Secondly Sourced Groundnuts From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_THIRDLY_SOURCED_FRUITS_LOCALLY_WITHIN_THE_DISTRICT(306, "Market Thirdly Sourced Fruits Locally (Within the District)"),
	MARKET_THIRDLY_SOURCED_FRUITS_FROM_NEIGHBORING_DISTRICTS(307, "Market Thirdly Sourced Fruits From Neighboring Districts"),
	MARKET_THIRDLY_SOURCED_FRUITS_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(308, "Market Thirdly Sourced Fruits From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_THIRDLY_SOURCED_TOMATOES_LOCALLY_WITHIN_THE_DISTRICT(309, "Market Thirdly Sourced Tomatoes Locally (Within the District)"),
	MARKET_THIRDLY_SOURCED_TOMATOES_FROM_NEIGHBORING_DISTRICTS(310, "Market Thirdly Sourced Tomatoes From Neighboring Districts"),
	MARKET_THIRDLY_SOURCED_TOMATOES_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(311, "Market Thirdly Sourced Tomatoes From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_THIRDLY_SOURCED_VEGETABLES_LOCALLY_WITHIN_THE_DISTRICT(312, "Market Thirdly Sourced Vegetables Locally (Within the District)"),
	MARKET_THIRDLY_SOURCED_VEGETABLES_FROM_NEIGHBORING_DISTRICTS(313, "Market Thirdly Sourced Vegetables From Neighboring Districts"),
	MARKET_THIRDLY_SOURCED_VEGETABLES_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(314, "Market Thirdly Sourced Vegetables From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_THIRDLY_SOURCED_BEANS_LOCALLY_WITHIN_THE_DISTRICT(315, "Market Thirdly Sourced Beans Locally (Within the District)"),
	MARKET_THIRDLY_SOURCED_BEANS_FROM_NEIGHBORING_DISTRICTS(316, "Market Thirdly Sourced Beans From Neighboring Districts"),
	MARKET_THIRDLY_SOURCED_BEANS_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(317, "Market Thirdly Sourced Beans From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_THIRDLY_SOURCED_CASSAVA_LOCALLY_WITHIN_THE_DISTRICT(318, "Market Thirdly Sourced Cassava Locally (Within the District)"),
	MARKET_THIRDLY_SOURCED_CASSAVA_FROM_NEIGHBORING_DISTRICTS(319, "Market Thirdly Sourced Cassava From Neighboring Districts"),
	MARKET_THIRDLY_SOURCED_CASSAVA_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(320, "Market Thirdly Sourced Cassava From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_THIRDLY_SOURCED_IRISH_POTATOES_LOCALLY_WITHIN_THE_DISTRICT(321, "Market Thirdly Sourced Irish Potatoes Locally (Within the District)"),
	MARKET_THIRDLY_SOURCED_IRISH_POTATOES_FROM_NEIGHBORING_DISTRICTS(322, "Market Thirdly Sourced Irish Potatoes From Neighboring Districts"),
	MARKET_THIRDLY_SOURCED_IRISH_POTATOES_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(323, "Market Thirdly Sourced Irish Potatoes From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_THIRDLY_SOURCED_SWEET_POTATOES_LOCALLY_WITHIN_THE_DISTRICT(324, "Market Thirdly Sourced Sweet Potatoes Locally (Within the District)"),
	MARKET_THIRDLY_SOURCED_SWEET_POTATOES_FROM_NEIGHBORING_DISTRICTS(325, "Market Thirdly Sourced Sweet Potatoes From Neighboring Districts"),
	MARKET_THIRDLY_SOURCED_SWEET_POTATOES_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(326, "Market Thirdly Sourced Sweet Potatoes From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_THIRDLY_SOURCED_MAIZE_LOCALLY_WITHIN_THE_DISTRICT(327, "Market Thirdly Sourced Maize Locally (Within the District)"),
	MARKET_THIRDLY_SOURCED_MAIZE_FROM_NEIGHBORING_DISTRICTS(328, "Market Thirdly Sourced Maize From Neighboring Districts"),
	MARKET_THIRDLY_SOURCED_MAIZE_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(329, "Market Thirdly Sourced Maize From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_THIRDLY_SOURCED_RICE_LOCALLY_WITHIN_THE_DISTRICT(330, "Market Thirdly Sourced Rice Locally (Within the District)"),
	MARKET_THIRDLY_SOURCED_RICE_FROM_NEIGHBORING_DISTRICTS(331, "Market Thirdly Sourced Rice From Neighboring Districts"),
	MARKET_THIRDLY_SOURCED_RICE_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(332, "Market Thirdly Sourced Rice From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_THIRDLY_SOURCED_GROUNDNUTS_LOCALLY_WITHIN_THE_DISTRICT(333, "Market Thirdly Sourced Groundnuts Locally (Within the District)"),
	MARKET_THIRDLY_SOURCED_GROUNDNUTS_FROM_NEIGHBORING_DISTRICTS(334, "Market Thirdly Sourced Groundnuts From Neighboring Districts"),
	MARKET_THIRDLY_SOURCED_GROUNDNUTS_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(335, "Market Thirdly Sourced Groundnuts From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_FIRSTLY_SOURCED_LIVE_CATTLE_LOCALLY_WITHIN_THE_DISTRICT(336, "Market Firstly Sourced Live Cattle Locally (Within the District)"),
	MARKET_FIRSTLY_SOURCED_LIVE_CATTLE_FROM_NEIGHBORING_DISTRICTS(337, "Market Firstly Sourced Live Cattle From Neighboring Districts"),
	MARKET_FIRSTLY_SOURCED_LIVE_CATTLE_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(338, "Market Firstly Sourced Live Cattle From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_FIRSTLY_SOURCED_LIVE_GOATS_LOCALLY_WITHIN_THE_DISTRICT(339, "Market Firstly Sourced Live Goats Locally (Within the District)"),
	MARKET_FIRSTLY_SOURCED_LIVE_GOATS_FROM_NEIGHBORING_DISTRICTS(340, "Market Firstly Sourced Live Goats From Neighboring Districts"),
	MARKET_FIRSTLY_SOURCED_LIVE_GOATS_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(341, "Market Firstly Sourced Live Goats From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_FIRSTLY_SOURCED_LIVE_CHICKENS_LOCALLY_WITHIN_THE_DISTRICT(342, "Market Firstly Sourced Live Chickens Locally (Within the District)"),
	MARKET_FIRSTLY_SOURCED_LIVE_CHICKENS_FROM_NEIGHBORING_DISTRICTS(343, "Market Firstly Sourced Live Chickens From Neighboring Districts"),
	MARKET_FIRSTLY_SOURCED_LIVE_CHICKENS_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(344, "Market Firstly Sourced Live Chickens From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_SECONDLY_SOURCED_LIVE_CATTLE_LOCALLY_WITHIN_THE_DISTRICT(345, "Market Secondly Sourced Live Cattle Locally (Within the District)"),
	MARKET_SECONDLY_SOURCED_LIVE_CATTLE_FROM_NEIGHBORING_DISTRICTS(346, "Market Secondly Sourced Live Cattle From Neighboring Districts"),
	MARKET_SECONDLY_SOURCED_LIVE_CATTLE_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(347, "Market Secondly Sourced Live Cattle From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_SECONDLY_SOURCED_LIVE_GOATS_LOCALLY_WITHIN_THE_DISTRICT(348, "Market Secondly Sourced Live Goats Locally (Within the District)"),
	MARKET_SECONDLY_SOURCED_LIVE_GOATS_FROM_NEIGHBORING_DISTRICTS(349, "Market Secondly Sourced Live Goats From Neighboring Districts"),
	MARKET_SECONDLY_SOURCED_LIVE_GOATS_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(350, "Market Secondly Sourced Live Goats From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_SECONDLY_SOURCED_LIVE_CHICKENS_LOCALLY_WITHIN_THE_DISTRICT(351, "Market Secondly Sourced Live Chickens Locally (Within the District)"),
	MARKET_SECONDLY_SOURCED_LIVE_CHICKENS_FROM_NEIGHBORING_DISTRICTS(352, "Market Secondly Sourced Live Chickens From Neighboring Districts"),
	MARKET_SECONDLY_SOURCED_LIVE_CHICKENS_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(353, "Market Secondly Sourced Live Chickens From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_THIRDLY_SOURCED_LIVE_CATTLE_LOCALLY_WITHIN_THE_DISTRICT(354, "Market Thirdly Sourced Live Cattle Locally (Within the District)"),
	MARKET_THIRDLY_SOURCED_LIVE_CATTLE_FROM_NEIGHBORING_DISTRICTS(355, "Market Thirdly Sourced Live Cattle From Neighboring Districts"),
	MARKET_THIRDLY_SOURCED_LIVE_CATTLE_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(356, "Market Thirdly Sourced Live Cattle From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_THIRDLY_SOURCED_LIVE_GOATS_LOCALLY_WITHIN_THE_DISTRICT(357, "Market Thirdly Sourced Live Goats Locally (Within the District)"),
	MARKET_THIRDLY_SOURCED_LIVE_GOATS_FROM_NEIGHBORING_DISTRICTS(358, "Market Thirdly Sourced Live Goats From Neighboring Districts"),
	MARKET_THIRDLY_SOURCED_LIVE_GOATS_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(359, "Market Thirdly Sourced Live Goats From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKET_THIRDLY_SOURCED_LIVE_CHICKENS_LOCALLY_WITHIN_THE_DISTRICT(360, "Market Thirdly Sourced Live Chickens Locally (Within the District)"),
	MARKET_THIRDLY_SOURCED_LIVE_CHICKENS_FROM_NEIGHBORING_DISTRICTS(361, "Market Thirdly Sourced Live Chickens From Neighboring Districts"),
	MARKET_THIRDLY_SOURCED_LIVE_CHICKENS_FROM_ACROSS_THE_BOARDERS_MOZAMBIQUE_ZAMBIA_TANZANIA(362, "Market Thirdly Sourced Live Chickens From Across The Boarders (Mozambique/Zambia/Tanzania)"),
	MARKETS_UNIT_COST_FOR_A_KILOGRAM_OF_FRUITS(363, "Market's Unit Cost for a Kilogram of Fruits"),
	MARKETS_UNIT_COST_FOR_A_KILOGRAM_OF_TOMATOES(364, "Market's Unit Cost for a Kilogram of Tomatoes"),
	MARKETS_UNIT_COST_FOR_A_KILOGRAM_OF_VEGETABLES(365, "Market's Unit Cost for a Kilogram of Vegetables"),
	MARKETS_UNIT_COST_FOR_A_KILOGRAM_OF_BEANS(366, "Market's Unit Cost for a Kilogram of Beans"),
	MARKETS_UNIT_COST_FOR_A_KILOGRAM_OF_CASSAVA(367, "Market's Unit Cost for a Kilogram of Cassava"),
	MARKETS_UNIT_COST_FOR_A_KILOGRAM_OF_IRISH_POTATOES(368, "Market's Unit Cost for a Kilogram of Irish Potatoes"),
	MARKETS_UNIT_COST_FOR_A_KILOGRAM_OF_SWEET_POTATOES(369, "Market's Unit Cost for a Kilogram of Sweet Potatoes"),
	MARKETS_UNIT_COST_FOR_A_KILOGRAM_OF_MAIZE(370, "Market's Unit Cost for a Kilogram of Maize"),
	MARKETS_UNIT_COST_FOR_A_KILOGRAM_OF_RICE(371, "Market's Unit Cost for a Kilogram of Rice"),
	MARKETS_UNIT_COST_FOR_A_KILOGRAM_OF_GROUNDNUTS(372, "Market's Unit Cost for a Kilogram of Groundnuts"),
	MARKETS_UNIT_COST_FOR_A_KILOGRAM_OF_FISH(373, "Market's Unit Cost for a Kilogram of Fish"),
	MARKETS_UNIT_COST_FOR_A_KILOGRAM_OF_BEEF(374, "Market's Unit Cost for a Kilogram of Beef"),
	MARKETS_UNIT_COST_FOR_A_KILOGRAM_OF_GOAT_MEAT(375, "Market's Unit Cost for a Kilogram of Goat Meat"),
	MARKETS_UNIT_COST_FOR_A_KILOGRAM_OF_PORK(376, "Market's Unit Cost for a Kilogram of Pork"),
	MARKETS_UNIT_COST_FOR_A_LIVE_CATTLE_OF_AVERAGE_SIZE(377, "Market's Unit Cost for a Live Cattle of Average Size"),
	MARKETS_UNIT_COST_FOR_A_LIVE_GOAT_OF_AVERAGE_SIZE(378, "Market's Unit Cost for a Live Goat of Average Size"),
	MARKETS_UNIT_COST_FOR_A_LIVE_CHICKEN_OF_AVERAGE_SIZE(379, "Market's Unit Cost for a Live Chicken of Average Size"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_FOOD_PRODUCTS_DELIVERED_TO_MARKET(380, "Market Had Signs Of Loss Or Damage of the Food Products Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_PLANT___BASED_FOOD_PRODUCTS_DELIVERED_TO_MARKET(381, "Market Had Signs Of Loss Or Damage of the Plant - Based Food Products Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_ANIMAL___BASED_FOOD_PRODUCTS_DELIVERED_TO_MARKET(382, "Market Had Signs Of Loss Or Damage of the Animal - Based Food Products Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_FRUITS_DELIVERED_TO_MARKET(383, "Market Had Signs Of Loss Or Damage of the Fruits Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_TOMATOES_DELIVERED_TO_MARKET(384, "Market Had Signs Of Loss Or Damage of the Tomatoes Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_VEGETABLES_DELIVERED_TO_MARKET(385, "Market Had Signs Of Loss Or Damage of the Vegetables Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_BEANS_DELIVERED_TO_MARKET(386, "Market Had Signs Of Loss Or Damage of the Beans Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_CASSAVA_DELIVERED_TO_MARKET(387, "Market Had Signs Of Loss Or Damage of the Cassava Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_IRISH_POTATOES_DELIVERED_TO_MARKE(388, "Market Had Signs Of Loss Or Damage of the Irish Potatoes Delivered To Marke"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_SWEET_POTATOES_DELIVERED_TO_MARKET(389, "Market Had Signs Of Loss Or Damage of the Sweet Potatoes Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_MAIZE_DELIVERED_TO_MARKET(390, "Market Had Signs Of Loss Or Damage of the Maize Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_RICE_DELIVERED_TO_MARKET(391, "Market Had Signs Of Loss Or Damage of the Rice Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_GROUNDNUTS_DELIVERED_TO_MARKET(392, "Market Had Signs Of Loss Or Damage of the Groundnuts Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_BEEF_DELIVERED_TO_MARKET(393, "Market Had Signs Of Loss Or Damage of the Beef Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_GOAT_MEAT_DELIVERED_TO_MARKET(394, "Market Had Signs Of Loss Or Damage of the Goat Meat Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_PORK_DELIVERED_TO_MARKET(395, "Market Had Signs Of Loss Or Damage of the Pork Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_THE_FISH_DELIVERED_TO_MARKET(396, "Market Had Signs Of Loss Or Damage of the Fish Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_FRUITS_DELIVERED_TO_MARKET(397, "Market Had Signs Of Loss Or Damage of Less Than Half of the Fruits Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_FRUITS_DELIVERED_TO_MARKET(398, "Market Had Signs Of Loss Or Damage of About Half of the Fruits Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_FRUITS_DELIVERED_TO_MARKET(399, "Market Had Signs Of Loss Or Damage of More Than Half of the Fruits Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_FRUITS_DELIVERED_TO_MARKET(400, "Market Had Signs Of Loss Or Damage of Practically All of the Fruits Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_TOMATOES_DELIVERED_TO_MARKET(401, "Market Had Signs Of Loss Or Damage of Less Than Half of the Tomatoes Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_TOMATOES_DELIVERED_TO_MARKET(402, "Market Had Signs Of Loss Or Damage of About Half of the Tomatoes Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_TOMATOES_DELIVERED_TO_MARKET(403, "Market Had Signs Of Loss Or Damage of More Than Half of the Tomatoes Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_TOMATOES_DELIVERED_TO_MARKET(404, "Market Had Signs Of Loss Or Damage of Practically All of the Tomatoes Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_VEGETABLES_DELIVERED_TO_MARKET(405, "Market Had Signs Of Loss Or Damage of Less Than Half of the Vegetables Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_VEGETABLES_DELIVERED_TO_MARKET(406, "Market Had Signs Of Loss Or Damage of About Half of the Vegetables Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_VEGETABLES_DELIVERED_TO_MARKET(407, "Market Had Signs Of Loss Or Damage of More Than Half of the Vegetables Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_VEGETABLES_DELIVERED_TO_MARKET(408, "Market Had Signs Of Loss Or Damage of Practically All of the Vegetables Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_BEANS_DELIVERED_TO_MARKET(409, "Market Had Signs Of Loss Or Damage of Less Than Half of the Beans Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_BEANS_DELIVERED_TO_MARKET(410, "Market Had Signs Of Loss Or Damage of About Half of the Beans Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_BEANS_DELIVERED_TO_MARKET(411, "Market Had Signs Of Loss Or Damage of More Than Half of the Beans Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_BEANS_DELIVERED_TO_MARKET(412, "Market Had Signs Of Loss Or Damage of Practically All of the Beans Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_CASSAVA_DELIVERED_TO_MARKET(413, "Market Had Signs Of Loss Or Damage of Less Than Half of the Cassava Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_CASSAVA_DELIVERED_TO_MARKET(414, "Market Had Signs Of Loss Or Damage of About Half of the Cassava Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_CASSAVA_DELIVERED_TO_MARKET(415, "Market Had Signs Of Loss Or Damage of More Than Half of the Cassava Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_CASSAVA_DELIVERED_TO_MARKET(416, "Market Had Signs Of Loss Or Damage of Practically All of the Cassava Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_IRISH_POTATOES_DELIVERED_TO_MARKET(417, "Market Had Signs Of Loss Or Damage of Less Than Half of the Irish Potatoes Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_IRISH_POTATOES_DELIVERED_TO_MARKET(418, "Market Had Signs Of Loss Or Damage of About Half of the Irish Potatoes Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_IRISH_POTATOES_DELIVERED_TO_MARKET(419, "Market Had Signs Of Loss Or Damage of More Than Half of the Irish Potatoes Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_IRISH_POTATOES_DELIVERED_TO_MARKET(420, "Market Had Signs Of Loss Or Damage of Practically All of the Irish Potatoes Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_SWEET_POTATOES_DELIVERED_TO_MARKET(421, "Market Had Signs Of Loss Or Damage of Less Than Half of the Sweet Potatoes Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_SWEET_POTATOES_DELIVERED_TO_MARKET(422, "Market Had Signs Of Loss Or Damage of About Half of the Sweet Potatoes Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_SWEET_POTATOES_DELIVERED_TO_MARKET(423, "Market Had Signs Of Loss Or Damage of More Than Half of the Sweet Potatoes Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_SWEET_POTATOES_DELIVERED_TO_MARKET(424, "Market Had Signs Of Loss Or Damage of Practically All of the Sweet Potatoes Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_MAIZE_DELIVERED_TO_MARKET(425, "Market Had Signs Of Loss Or Damage of Less Than Half of the Maize Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_MAIZE_DELIVERED_TO_MARKET(426, "Market Had Signs Of Loss Or Damage of About Half of the Maize Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_MAIZE_DELIVERED_TO_MARKET(427, "Market Had Signs Of Loss Or Damage of More Than Half of the Maize Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_MAIZE_DELIVERED_TO_MARKET(428, "Market Had Signs Of Loss Or Damage of Practically All of the Maize Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_RICE_DELIVERED_TO_MARKET(429, "Market Had Signs Of Loss Or Damage of Less Than Half of the Rice Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_RICE_DELIVERED_TO_MARKET(430, "Market Had Signs Of Loss Or Damage of About Half of the Rice Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_RICE_DELIVERED_TO_MARKET(431, "Market Had Signs Of Loss Or Damage of More Than Half of the Rice Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_RICE_DELIVERED_TO_MARKET(432, "Market Had Signs Of Loss Or Damage of Practically All of the Rice Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_GROUNDNUTS_DELIVERED_TO_MARKET(433, "Market Had Signs Of Loss Or Damage of Less Than Half of the Groundnuts Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_GROUNDNUTS_DELIVERED_TO_MARKET(434, "Market Had Signs Of Loss Or Damage of About Half of the Groundnuts Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_GROUNDNUTS_DELIVERED_TO_MARKET(435, "Market Had Signs Of Loss Or Damage of More Than Half of the Groundnuts Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_GROUNDNUTS_DELIVERED_TO_MARKET(436, "Market Had Signs Of Loss Or Damage of Practically All of the Groundnuts Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_BEEF_DELIVERED_TO_MARKET(437, "Market Had Signs Of Loss Or Damage of Less Than Half of the Beef Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_BEEF_DELIVERED_TO_MARKET(438, "Market Had Signs Of Loss Or Damage of About Half of the Beef Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_BEEF_DELIVERED_TO_MARKET(439, "Market Had Signs Of Loss Or Damage of More Than Half of the Beef Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_BEEF_DELIVERED_TO_MARKET(440, "Market Had Signs Of Loss Or Damage of Practically All of the Beef Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_GOAT_MEAT_DELIVERED_TO_MARKET(441, "Market Had Signs Of Loss Or Damage of Less Than Half of the Goat Meat Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_GOAT_MEAT_DELIVERED_TO_MARKET(442, "Market Had Signs Of Loss Or Damage of About Half of the Goat Meat Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_GOAT_MEAT_DELIVERED_TO_MARKET(443, "Market Had Signs Of Loss Or Damage of More Than Half of the Goat Meat Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_GOAT_MEAT_DELIVERED_TO_MARKET(444, "Market Had Signs Of Loss Or Damage of Practically All of the Goat Meat Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_PORK_DELIVERED_TO_MARKET(445, "Market Had Signs Of Loss Or Damage of Less Than Half of the Pork Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_PORK_DELIVERED_TO_MARKET(446, "Market Had Signs Of Loss Or Damage of About Half of the Pork Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_PORK_DELIVERED_TO_MARKET(447, "Market Had Signs Of Loss Or Damage of More Than Half of the Pork Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_PORK_DELIVERED_TO_MARKET(448, "Market Had Signs Of Loss Or Damage of Practically All of the Pork Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_LESS_THAN_HALF_OF_THE_FISH_DELIVERED_TO_MARKET(449, "Market Had Signs Of Loss Or Damage of Less Than Half of the Fish Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_ABOUT_HALF_OF_THE_FISH_DELIVERED_TO_MARKET(450, "Market Had Signs Of Loss Or Damage of About Half of the Fish Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_MORE_THAN_HALF_OF_THE_FISH_DELIVERED_TO_MARKET(451, "Market Had Signs Of Loss Or Damage of More Than Half of the Fish Delivered To Market"),
	MARKET_HAD_SIGNS_OF_LOSS_OR_DAMAGE_OF_PRACTICALLY_ALL_OF_THE_FISH_DELIVERED_TO_MARKET(452, "Market Had Signs Of Loss Or Damage of Practically All of the Fish Delivered To Market"),
	ALL_MARKET_AGRO_DEALER_SHOPS_ARE_OPEN(453, "All Market Agro Dealer Shops Are Open"),
	A_FEW_MARKET_AGRO_DEALER_SHOPS_ARE_OPEN(454, "A Few Market Agro Dealer Shops Are Open"),
	NO_MARKET_AGRO_DEALER_SHOP_IS_OPEN(455, "No Market Agro Dealer Shop Is Open");

    private PhenomenonTypeEnum(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public int getId() {
        return id;
    }
    
    public String getName() {
        return name;
    }    

    private final int id;
    private final String name;
}